application: fx-leg
version: 1
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "5m"

builtins:
- deferred: on
- remote_api: on
- appstats: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

handlers:
- url: /admin/console/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /static
  static_dir: static

- url: /(favicon\.ico)
  mime_type: image/png
  static_files: static/\1
  upload: static/favicon\.ico

- url: /(robots\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/robots\.txt

- url: /(img|css|js|downloads|fonts)/(.*)
  static_files: static/\1/\2
  upload: static/(img|css|js|downloads|fonts)/(.*)

- url: /admin
  static_files: static/admin.html
  upload: static/admin.html
  login: admin

- url: .*
  script: main.app
  secure: always